title: OpenEMR
baseURL: https://www.open-emr.org/
theme: openemr
languageCode: en-us
copyright: OpenEMR Foundation, Inc
disqusShortname: openemr
googleAnalytics: UA-8316288-7
enableGitInfo: true
ignoreFiles:
  - _files%
  - _cache$
taxonomies:
  tag: ""
  category: ""
menu:
  main:
    - identifier: features
      name: Features
      url: http://localhost:1313/wiki/index.php/OpenEMR_Features
      weight: 1
    - identifier: demo
      name: Demo
      url: /demo
      weight: 2
    - identifier: download
      name: Download
      url: http://localhost:1313/wiki/index.php/OpenEMR_Downloads
      weight: 3
    - identifier: module
      name: Modules
      url: /modules
      weight: 4
    - identifier: blog
      name: Blog
      url: /blog
      weight: 5
    - identifier: wiki
      name: Docs
      url: /wiki
      weight: 6
    - identifier: forum
      name: Forum
      url: https://community.open-emr.org/
      weight: 7
    - identifier: chat
      name: Chat
      url: http://localhost:1313/chat
      weight: 8
    - identifier: support
      name: Support
      weight: 9
    - identifier: cost_and_support
      parent: support
      name: Costs and Support Options
      url: /support
      weight: 1
    - identifier: community_support
      parent: support
      name: Community Support
      weight: 2
      url: https://community.open-emr.org
    - identifier: chat_support
      parent: support
      name: Chat
      url: http://localhost:1313/chat
      weight: 3
    - identifier: psv
      parent: support
      name: Professional Support Vendors
      url: /wiki/index.php/Professional_Support
      weight: 4
    - identifier: howto
      parent: support
      name: How-To Guides
      url: /wiki/index.php/OpenEMR_5.0.1_Users_Guide
      weight: 5
    - identifier: donate
      name: Donate
      weight: 10
      url: /give
      pre: '<i class="fa fa-heart fa-sm"></i>&nbsp;'
      params:
        anchorClass: 'btn btn-danger btn-sm mx-4'
params:
  # Required theme-specific variables
  twitterImage: /images/test.jpg
  coverImageStyle: standard
  twitterCardType: summary
  intro: "true"
  headline: OpenEMR
  description: The world's leading open-source electronic medical record and practice management software.
  github: "https://github.com/openemr"
  linkedin: ""
  gplus: https://plus.google.com/106799034872780958301
  twitter: https://twitter.com/openemr
  facebook: https://www.facebook.com/OpenEMR-181315115284266
  stackoverflow: ""
  email: blog@oemr.org
  opengraph: true
  shareTwitter: true
  shareFacebook: true
  shareGooglePlus: true
  shareLinkedIn: true
  dateFormat: Mon, Jan 2, 2006
  highlightJsUrl: ""
  highlightJsLocalUrl: ""
  author:
    name: OpenEMR
    twitter: openemr
  demoUrl: demo
  downloadUrl: https://www.open-emr.org/wiki/index.php/OpenEMR_Downloads
permalinks:
  post: /:filename/
