# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "OpenEMR"
license = "None"
licenselink = "https://github.com/openemr/website-theme/blob/master/LICENSE.md"
description = ""
homepage = "http://open-emr.org/"
tags = []
features = []
min_version = "0.27.1"

[author]
  name = "Robert Down"
  homepage = "robertdown.net"
